---
# =============================================================================
# Apache Handlers
# =============================================================================

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted

- name: Reload Apache
  systemd:
    name: apache2
    state: reloaded